version: '3'
services:
  srt-frontend:
    image: 127.0.0.1:5000/frontend:2
    container_name: srt-frontend
    restart: always
    ports:
      - 80:81
    deploy:
      mode: replicated
      replicas: 10
      placement:
          constraints:
              - node.role == worker